import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './overrides.css';

const money=(p:number)=>`GH₵ ${(p/100).toFixed(2)}`;
type CartLine=PosProduct&{quantity:number};
type User={id:string;name:string;username:string;role:'owner'|'cashier'};
type Sale={id:string;receiptNumber:string;totalPesewas:number;status:string;createdAt:string;staffId:string;staffName:string;paymentMethod:string};

function Login({onLogin}:{onLogin:(u:User)=>void}){const[username,setUsername]=useState('owner');const[pin,setPin]=useState('1234');const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const u=await window.pos.session.login({username,pin});if(u)onLogin(u);else setError('Incorrect username or PIN.')}catch{setError('Unable to access the local database.')}};return <div className="login-page"><form className="login-card" onSubmit={submit}><div className="brand-mark large">P</div><p className="eyebrow">RETAIL POS</p><h1>Sign in to your shop</h1><p className="muted">Offline checkout remains available when the internet is down.</p><label>Username<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>PIN<input type="password" inputMode="numeric" maxLength={8} value={pin} onChange={e=>setPin(e.target.value)}/></label>{error&&<div className="notice error">{error}</div>}<button className="complete">Sign in <span>→</span></button><small className="login-hint">Initial development account: owner / 1234. Change this before deployment.</small></form></div>}

function App(){const[user,setUser]=useState<User|null>(null);const[products,setProducts]=useState<PosProduct[]>([]);const[categories,setCategories]=useState<{id:string;name:string}[]>([]);const[active,setActive]=useState<'pos'|'inventory'|'sales'>('pos');const[query,setQuery]=useState('');const[category,setCategory]=useState('All');const[cart,setCart]=useState<CartLine[]>([]);const[payment,setPayment]=useState<'cash'|'momo'>('cash');const[tendered,setTendered]=useState('');const[momoReference,setMomoReference]=useState('');const[notice,setNotice]=useState('');const[success,setSuccess]=useState<{receipt:string;total:number}|null>(null);const[pendingSync,setPendingSync]=useState(0);const[sales,setSales]=useState<Sale[]>([]);const[stockProduct,setStockProduct]=useState<PosProduct|null>(null);const[stockDelta,setStockDelta]=useState('');const[stockReason,setStockReason]=useState('Manual adjustment');const[newProduct,setNewProduct]=useState(false);const[form,setForm]=useState({name:'',barcode:'',price:'',stock:'',threshold:'5',categoryId:''});
const refresh=async()=>{const[p,c,h]=await Promise.all([window.pos.catalog.products(),window.pos.catalog.categories(),window.pos.health()]);setProducts(p);setCategories(c);setPendingSync(h.pendingSync)};
useEffect(()=>{if(user)refresh()},[user]);
useEffect(()=>{if(user&&active==='sales')window.pos.sales.list({}).then(setSales)},[user,active]);
const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.barcode??''}`.toLowerCase().includes(query.toLowerCase())&&(category==='All'||p.category===category)),[products,query,category]);const total=cart.reduce((s,x)=>s+x.pricePesewas*x.quantity,0);const cash=Math.round((Number(tendered)||0)*100);const change=Math.max(0,cash-total);
function add(p:PosProduct){setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:Math.min(i.quantity+1,p.quantityInStock)}:i):[...c,{...p,quantity:1}]})}
function qty(id:string,d:number){setCart(c=>c.flatMap(x=>{if(x.id!==id)return[x];const q=x.quantity+d;return q<=0?[]:q<=x.quantityInStock?[{...x,quantity:q}]:[x]}))}
async function complete(){setNotice('');if(!cart.length)return setNotice('Add at least one product.');if(payment==='cash'&&cash<total)return setNotice(`Cash received is ${money(total-cash)} short.`);if(payment==='momo'&&!momoReference.trim())return setNotice('Mobile Money reference is required.');try{const r=await window.pos.sales.checkout({staffId:user!.id,items:cart.map(x=>({productId:x.id,quantity:x.quantity})),paymentMethod:payment,amountTenderedPesewas:payment==='cash'?cash:total,momoReference:payment==='momo'?momoReference.trim():undefined});setSuccess({receipt:r.receiptNumber,total:r.totalPesewas});setCart([]);setTendered('');setMomoReference('');await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Sale failed. No changes were committed.')}}
async function adjust(){if(!stockProduct)return;try{await window.pos.inventory.adjustStock({productId:stockProduct.id,quantityDelta:Number(stockDelta),reason:stockReason,actorId:user!.id});setStockProduct(null);setStockDelta('');await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Stock adjustment failed.')}}
async function create(){try{await window.pos.catalog.createProduct({name:form.name,barcode:form.barcode,pricePesewas:Math.round(Number(form.price)*100),quantityInStock:Number(form.stock),lowStockThreshold:Number(form.threshold),categoryId:form.categoryId||null,actorId:user!.id});setNewProduct(false);setForm({name:'',barcode:'',price:'',stock:'',threshold:'5',categoryId:''});await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Could not create product.')}}
if(!user)return <Login onLogin={setUser}/>;const low=products.filter(p=>p.quantityInStock<=p.lowStockThreshold);return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">P</div><div><b>Retail POS</b><span>Shop A · Cosmetics & Provisions</span></div></div><nav><button className={active==='pos'?'nav active':'nav'} onClick={()=>setActive('pos')}>⌘ Point of Sale</button><button className={active==='inventory'?'nav active':'nav'} onClick={()=>setActive('inventory')}>▦ Inventory</button><button className={active==='sales'?'nav active':'nav'} onClick={()=>setActive('sales')}>▤ Sales History</button></nav><div className="sidebar-bottom"><div className="sync"><i/><div><b>Offline ready</b><small>{pendingSync?`${pendingSync} queued for sync`:'Local database active'}</small></div></div><div className="user"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.role}</small></div><button onClick={()=>setUser(null)}>↪</button></div></div></aside><main className="main"><header className="header"><div><span className="crumb">SHOP A / {active.toUpperCase()}</span><h1>{active==='pos'?'Point of Sale':active==='inventory'?'Inventory':'Sales History'}</h1></div><div className="header-actions"><div className="connection"><i/> Offline <span>·</span>{pendingSync?`${pendingSync} pending sync`:'Ready'}</div><button className="profile">{user.name[0]}</button></div></header>
{active==='pos'&&<section className="pos-layout"><div className="catalog"><div className="search"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search product or scan barcode..."/></div><div className="categories"><button className={category==='All'?'chip selected':'chip'} onClick={()=>setCategory('All')}>All</button>{categories.map(c=><button key={c.id} className={category===c.name?'chip selected':'chip'} onClick={()=>setCategory(c.name)}>{c.name}</button>)}</div><div className="product-grid">{filtered.map(p=><button className="product" key={p.id} disabled={!p.quantityInStock} onClick={()=>add(p)}><div className="product-icon">{p.name[0]}</div><div className="product-info"><b>{p.name}</b><small>{p.category??'Uncategorised'}</small><strong>{money(p.pricePesewas)}</strong></div><span className={p.quantityInStock<=p.lowStockThreshold?'stock low':'stock'}>{p.quantityInStock} left</span></button>)}</div></div><aside className="cart-panel"><div className="cart-head"><div><h2>Current Sale</h2><span>{cart.reduce((s,x)=>s+x.quantity,0)} units</span></div><button className="clear" onClick={()=>setCart([])}>Clear</button></div><div className="cart-lines">{!cart.length?<div className="empty"><div>＋</div><b>Cart is empty</b><span>Scan or select a product to begin</span></div>:cart.map(x=><div className="cart-line" key={x.id}><div className="line-icon">{x.name[0]}</div><div className="line-main"><b>{x.name}</b><small>{money(x.pricePesewas)} each</small><div className="qty"><button onClick={()=>qty(x.id,-1)}>−</button><span>{x.quantity}</span><button onClick={()=>qty(x.id,1)}>+</button></div></div><strong>{money(x.pricePesewas*x.quantity)}</strong></div>)}</div><div className="checkout"><div className="summary"><span>Subtotal</span><b>{money(total)}</b></div><div className="total"><span>Total</span><b>{money(total)}</b></div><div className="payment-tabs"><button className={payment==='cash'?'pay active':'pay'} onClick={()=>setPayment('cash')}>Cash</button><button className={payment==='momo'?'pay active':'pay'} onClick={()=>setPayment('momo')}>Mobile Money</button></div>{payment==='cash'?<div className="tender"><label>Cash received</label><input inputMode="decimal" value={tendered} onChange={e=>setTendered(e.target.value)} placeholder="0.00"/><span>Change <b>{money(change)}</b></span></div>:<div className="tender"><label>MoMo transaction reference</label><input value={momoReference} onChange={e=>setMomoReference(e.target.value)} placeholder="Transaction reference"/></div>}<button className="complete" onClick={complete}>Complete Sale <span>→</span></button>{notice&&<div className="notice error">{notice}</div>}</div></aside></section>}
{active==='inventory'&&<section className="page"><div className="metric-row"><div className="metric"><span>Products</span><b>{products.length}</b></div><div className="metric"><span>Low stock</span><b>{low.length}</b></div><div className="metric"><span>Out of stock</span><b>{products.filter(p=>p.quantityInStock===0).length}</b></div>{user.role==='owner'&&<button className="complete" onClick={()=>setNewProduct(true)}>+ Add Product</button>}</div><div className="panel"><div className="panel-head"><div><h2>Products</h2><span>Live data from local SQLite</span></div></div><table><thead><tr><th>Product</th><th>Barcode</th><th>Category</th><th>Price</th><th>Stock</th>{user.role==='owner'&&<th>Action</th>}</tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.barcode??'—'}</td><td>{p.category??'—'}</td><td>{money(p.pricePesewas)}</td><td><span className={p.quantityInStock<=p.lowStockThreshold?'badge danger':'badge'}>{p.quantityInStock}</span></td>{user.role==='owner'&&<td><button className="clear" onClick={()=>setStockProduct(p)}>Adjust stock</button></td>}</tr>)}</tbody></table></div></section>}
{active==='sales'&&<section className="page"><div className="metric-row"><div className="metric"><span>Transactions</span><b>{sales.length}</b></div><div className="metric"><span>Cash</span><b>{money(sales.filter(s=>s.paymentMethod==='cash').reduce((a,s)=>a+s.totalPesewas,0))}</b></div><div className="metric"><span>Mobile Money</span><b>{money(sales.filter(s=>s.paymentMethod==='momo').reduce((a,s)=>a+s.totalPesewas,0))}</b></div><div className="metric"><span>Total</span><b>{money(sales.reduce((a,s)=>a+s.totalPesewas,0))}</b></div></div><div className="panel"><div className="panel-head"><div><h2>Sales</h2><span>Latest 500 transactions</span></div></div><table><thead><tr><th>Receipt</th><th>Date</th><th>Cashier</th><th>Payment</th><th>Total</th><th>Status</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td><b>{s.receiptNumber}</b></td><td>{new Date(s.createdAt).toLocaleString()}</td><td>{s.staffName}</td><td>{s.paymentMethod==='momo'?'Mobile Money':'Cash'}</td><td>{money(s.totalPesewas)}</td><td><span className="badge">{s.status}</span></td></tr>)}</tbody></table>{!sales.length&&<div className="empty">No sales recorded yet.</div>}</div></section>}
</main>{newProduct&&<div className="modal-backdrop"><div className="modal"><div className="panel-head"><div><h2>Add Product</h2><span>Owner action</span></div><button className="clear" onClick={()=>setNewProduct(false)}>Close</button></div><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Barcode<input value={form.barcode} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Uncategorised</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><label>Price (GH₵)<input inputMode="decimal" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Opening stock<input inputMode="numeric" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label></div><label>Low-stock threshold<input inputMode="numeric" value={form.threshold} onChange={e=>setForm({...form,threshold:e.target.value})}/></label><button className="complete" onClick={create}>Create Product</button></div></div>}{stockProduct&&<div className="modal-backdrop"><div className="modal"><div className="panel-head"><div><h2>Adjust Stock</h2><span>{stockProduct.name} · current {stockProduct.quantityInStock}</span></div><button className="clear" onClick={()=>setStockProduct(null)}>Close</button></div><label>Quantity change (+ to add, − to remove)<input inputMode="numeric" value={stockDelta} onChange={e=>setStockDelta(e.target.value)} placeholder="e.g. 10 or -2"/></label><label>Reason<input value={stockReason} onChange={e=>setStockReason(e.target.value)}/></label><button className="complete" onClick={adjust}>Save Adjustment</button></div></div>}{success&&<div className="modal-backdrop"><div className="success-card"><div className="success-icon">✓</div><p className="eyebrow">SALE COMPLETED</p><h2>Payment received</h2><strong>{money(success.total)}</strong><span>Receipt {success.receipt}</span><button className="complete" onClick={()=>setSuccess(null)}>Done</button></div></div>}{notice&&active!=='pos'&&<div className="toast notice error">{notice}</div>}</div>}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
